### ISSUE TITLE
acron 7 support

### ISSUE THREAD

**Issue by unional** [acornjs/acorn-bigint#5]
Currently it lists `acron@^6.0.0` in peer deps

**Comment by adrianheine** [comment]
acorn supports bigint [since 6.1](https://github.com/acornjs/acorn/blob/master/acorn/CHANGELOG.md#620-2019-07-04).

**Comment by unional** [comment]
How to enable it? The parse fails without using this library:

```
console.log src/tersifyAcorn/tersifyAcron.ts:10
    function () { return 1n; }

  console.log src/tersifyAcorn/tersifyAcron.ts:15
    error SyntaxError: Identifier directly after number (1:23)
        at Parser.pp$4.raise (/Users/hwong/code/unional/tersify/node_modules/acorn/dist/acorn.js:2840:15)
        at Parser.pp$9.readNumber (/Users/hwong/code/unional/tersify/node_modules/acorn/dist/acorn.js:4683:61)
        at Parser.pp$9.getTokenFromCode (/Users/hwong/code/unional/tersify/node_modules/acorn/dist/acorn.js:4541:19)
        at Parser.pp$9.readToken (/Users/hwong/code/unional/tersify/node_modules/acorn/dist/acorn.js:4305:17)
        at Parser.pp$9.nextToken (/Users/hwong/code/unional/tersify/node_modules/acorn/dist/acorn.js:4296:17)
        at Parser.pp$9.next (/Users/hwong/code/unional/tersify/node_modules/acorn/dist/acorn.js:4253:10)
        at Parser.pp$1.parseReturnStatement (/Users/hwong/code/unional/tersify/node_modules/acorn/dist/acorn.js:998:10)
        at Parser.pp$1.parseStatement (/Users/hwong/code/unional/tersify/node_modules/acorn/dist/acorn.js:835:37)
        at Parser.pp$1.parseBlock (/Users/hwong/code/unional/tersify/node_modules/acorn/dist/acorn.js:1161:23)
        at Parser.pp$3.parseFunctionBody (/Users/hwong/code/unional/tersify/node_modules/acorn/dist/acorn.js:2686:24) {
      pos: 23,
      loc: Position { line: 1, column: 23 },
      raisedAt: 23
```

**Comment by unional** [comment]
nevermind. found it:

`parseExpressionAt(`(${fnStr})`, 0, { ecmaVersion: 11 })`

Thanks!
